### ISSUE TITLE
Downloadlink doesn't work anymore?

### ISSUE THREAD

**Issue by gdm2** [simonmoreau/align-tag#1]
Hi Simon, 

It seems that the downloadlink to the Autodesk App Exchange doesn't work anymore. This is where it leads me: 

![image](https://user-images.githubusercontent.com/17804567/45022026-70609a80-b033-11e8-9cb7-f8356bce84c4.png)

Link: https://apps.autodesk.com/RVT/en/Detail/Index?id=2903508825431715905&appLang=en&os=Win32_64

Am I doing something wrong or is my country (The Netherlands) blocking something?

Looking forward!

Good work btw ;)

**Comment by simonmoreau** [comment]
I had an issue within Align that I had to solve before republishing it on the App Store.

Align is now reviewed by Autodesk and should be back on the App Store in a few days.

Best regards,

**Comment by ArjanPeeters** [comment]
Still no download link (also the Netherlands)
