### ISSUE TITLE
the AlignTag.dll isn't uploaded in the here

### ISSUE THREAD

**Issue by Jopa21** [simonmoreau/align-tag#2]
I can't successfully install the add-in, since the AlignTag.dll is not uploaded in here and the Autodesk page is no longer hosting the installer. It seams like an awesome add-in. Hopefully this issue can be resolved and (it might just be me) but the manual installation process is kind of confusing. 
Thanks!

**Comment by simonmoreau** [comment]
I had an issue within Align that I had to solve before republishing it on the App Store.

Align is now reviewed by Autodesk and should be back on the App Store in a few days.

Best regards,
