### ISSUE TITLE
Room Tags with Leaders Don't Work

### ISSUE THREAD

**Issue by estimmel** [simonmoreau/align-tag#3]
When applying this to Room Tags, it looks like the add-in is trying to work around the issue in previous versions (at least 1.3.0) where Room Tags were aligned to the center of the bounding box of the tag and leader combined and would produce errors if that pulled the endpoint of the leader outside of the room. as shown below.

![AlignRoomTags02](https://user-images.githubusercontent.com/1373088/54320109-1a078200-45a9-11e9-94cb-a78b38905af9.png)

In this case, I can see that it's turning off leaders, trying to do something, and then putting the tags right back where they were with leaders turned on. In other words, it's not showing an error, but it's also not aligning the tags.

When the Room Tags have no leader line and are forced to align in a way that moves them outside of the room, we do get an error and the command fails.

![AlignRoomTags03](https://user-images.githubusercontent.com/1373088/54319918-8766e300-45a8-11e9-8a1d-568a0092b3b0.png)

In version 1.3.0, I could select the tags with leaders, turn off all tags in the Option bar, run the alignment command, and then re-enable leaders. This is/was clumsy, but workable. Am I missing something about the latest version? Is there a way to get this to work on Room Tags that I'm not seeing?

**Comment by simonmoreau** [comment]
This should now be fixed with the new version
